---
language: go

env:
  - PACKAGE=marathon-dynamic
  - PACKAGE=mesos-agent
  - PACKAGE=mesos-agent-dynamic
  - PACKAGE=mesos-master
  - PACKAGE=mesos-master-dynamic
  - PACKAGE=mesos
  - PACKAGE=mesos-agent-27.1
  - PACKAGE=mesos-agent-dynamic-27.1
  - PACKAGE=mesos-master-27.1
  - PACKAGE=mesos-master-dynamic=27.1
  - PACKAGE=mesos-27.1

  # we don't build Marathon on the Travis infrastructure because it takes
  # *forever*
  # - PACKAGE=marathon

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # hammer
      - rpm
      - g++-4.8
      - openjdk-7-jdk
      - build-essential 
      - python-dev 
      - python-boto 
      - libcurl4-nss-dev 
      - libsasl2-dev 
      - libsasl2-modules 
      - maven 
      - libapr1-dev 
      - libsvn-dev

install:
  # packages for packaging
  - go get -v github.com/asteris-llc/hammer
  - gem install fpm

script:
  - hammer build --output=/tmp/out $PACKAGE

after_failure:
  - tail logs/*

deploy:
  provider: script
  script: /bin/bash scripts/bintray.sh /tmp/out
  on:
    branch: master
